---
apiVersion: v1
kind: Service
metadata:
  name: centaurid-api
  namespace: centauri
  labels:
    app: centauri
    component: peer
spec:
  type: ClusterIP
  selector:
    app: centauri
    component: peer
  ports:
    - protocol: TCP
      port: 5666
      targetPort: 5666
      name: http-centauri