---
apiVersion: v1
kind: Service
metadata:
  name: centaurid-peer
  namespace: centauri
  labels:
    app: centauri
    component: peer
spec:
  type: ClusterIP
  selector:
    app: centauri
    component: peer
  ports:
    - protocol: TCP
      port: 5664
      targetPort: 5664
      name: tcp-data
    - protocol: TCP
      port: 5665
      targetPort: 5665
      name: tcp-centauri
    - protocol: UDP
      port: 5665
      targetPort: 5665
      name: udp-centauri